<script lang="ts">
	let activeTab = $state<'terms' | 'privacy'>('terms');
</script>

<div class="mx-auto min-h-screen max-w-[680px] px-4 py-8">
	<a href="/" class="text-xs text-[#64748b] transition hover:text-[#22d3ee]">&larr; back to chat</a>
	<h1 class="mt-4 text-2xl font-light tracking-tight text-[#e2e8f0]">Legal</h1>

	<div class="mt-6 flex gap-4 border-b border-[#1a1a1a]">
		<button
			onclick={() => (activeTab = 'terms')}
			class="border-b-2 pb-3 text-sm transition {activeTab === 'terms' ? 'border-[#22d3ee] text-[#22d3ee]' : 'border-transparent text-[#64748b] hover:text-[#e2e8f0]'}"
		>
			Terms of Use
		</button>
		<button
			onclick={() => (activeTab = 'privacy')}
			class="border-b-2 pb-3 text-sm transition {activeTab === 'privacy' ? 'border-[#22d3ee] text-[#22d3ee]' : 'border-transparent text-[#64748b] hover:text-[#e2e8f0]'}"
		>
			Privacy Policy
		</button>
	</div>

	<div class="mt-6 space-y-6 text-sm leading-relaxed text-[#94a3b8]">
		{#if activeTab === 'terms'}
			<section>
				<h2 class="mb-3 text-lg font-medium text-[#e2e8f0]">Terms of Use</h2>
				<p class="mb-4 text-xs text-[#64748b]">Last updated: May 15, 2026</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">1. Acceptance of Terms</h3>
				<p class="mb-4">By accessing or using Studymate ("the Service"), you agree to be bound by these Terms of Use. If you do not agree, do not use the Service.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">2. Eligibility</h3>
				<p class="mb-4">The Service is intended for students and educators. You must be at least 16 years old to create an account.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">3. User Accounts</h3>
				<p class="mb-4">You are responsible for maintaining the confidentiality of your account credentials. All activities under your account are your responsibility.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">4. Acceptable Use</h3>
				<p class="mb-4">You agree not to:</p>
				<ul class="mb-4 ml-5 list-disc space-y-1">
					<li>Upload copyrighted material you do not have permission to share</li>
					<li>Use the Service for any illegal or unauthorized purpose</li>
					<li>Attempt to access other users' data or accounts</li>
					<li>Automate access to the Service (scraping, bots)</li>
					<li>Distribute malware or harmful content</li>
				</ul>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">5. User Content</h3>
				<p class="mb-4">You retain ownership of content you upload. By uploading, you grant the Service a license to store and process your content solely to provide the Service. You are responsible for ensuring you have the right to upload all materials.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">6. AI-Generated Content</h3>
				<p class="mb-4">Responses generated by the AI assistant are provided for educational purposes only. They may contain inaccuracies. Always verify important information with official sources. The Service does not guarantee the accuracy, completeness, or reliability of AI-generated content.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">7. Intellectual Property</h3>
				<p class="mb-4">The Service, its design, code, and branding are protected by intellectual property rights. You may not reproduce or distribute any part of the Service without permission.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">8. Limitation of Liability</h3>
				<p class="mb-4">The Service is provided "as is" without warranties. We are not liable for any damages arising from your use of the Service, including but not limited to data loss, service interruption, or inaccurate AI responses.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">9. Termination</h3>
				<p class="mb-4">We reserve the right to suspend or terminate accounts that violate these terms without prior notice.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">10. Changes to Terms</h3>
				<p class="mb-4">We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">11. Contact</h3>
				<p>For questions about these terms, contact us through the Service.</p>
			</section>
		{:else}
			<section>
				<h2 class="mb-3 text-lg font-medium text-[#e2e8f0]">Privacy Policy</h2>
				<p class="mb-4 text-xs text-[#64748b]">Last updated: May 15, 2026</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">1. Information We Collect</h3>
				<p class="mb-4">We collect the following information:</p>
				<ul class="mb-4 ml-5 list-disc space-y-1">
					<li><strong class="text-[#e2e8f0]">Account data:</strong> Name, email address, and authentication credentials</li>
					<li><strong class="text-[#e2e8f0]">Usage data:</strong> Conversations, uploaded files, and interaction history</li>
					<li><strong class="text-[#e2e8f0]">Technical data:</strong> Browser type, IP address, and device information</li>
				</ul>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">2. How We Use Your Data</h3>
				<p class="mb-4">Your data is used to:</p>
				<ul class="mb-4 ml-5 list-disc space-y-1">
					<li>Provide and improve the Service</li>
					<li>Process your uploaded course materials for AI-assisted responses</li>
					<li>Maintain conversation history for your convenience</li>
					<li>Ensure account security and prevent abuse</li>
				</ul>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">3. Data Storage</h3>
				<p class="mb-4">Your data is stored securely using encrypted databases. Course materials are processed and stored as vector embeddings for retrieval-augmented generation (RAG). Your conversations and files are isolated per user and not accessible to others.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">4. Third-Party Services</h3>
				<p class="mb-4">The Service uses the following third-party providers:</p>
				<ul class="mb-4 ml-5 list-disc space-y-1">
					<li><strong class="text-[#e2e8f0]">Groq:</strong> AI model inference for generating responses</li>
					<li><strong class="text-[#e2e8f0]">Neon/Turso:</strong> Database hosting</li>
					<li><strong class="text-[#e2e8f0]">Cloudflare:</strong> Application hosting and CDN</li>
				</ul>
				<p class="mb-4">These providers have their own privacy policies. We share only the minimum data necessary to operate the Service.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">5. Data Sharing</h3>
				<p class="mb-4">We do not sell, trade, or rent your personal data. Your uploaded course materials and conversations are never shared with other users. We may disclose data if required by law.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">6. Data Retention</h3>
				<p class="mb-4">Your data is retained as long as your account is active. You may delete your uploaded materials at any time. If you delete your account, all associated data will be removed.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">7. Your Rights</h3>
				<p class="mb-4">You have the right to:</p>
				<ul class="mb-4 ml-5 list-disc space-y-1">
					<li>Access your personal data</li>
					<li>Correct inaccurate data</li>
					<li>Delete your data and account</li>
					<li>Export your uploaded materials and conversations</li>
					<li>Object to processing of your data</li>
				</ul>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">8. Security</h3>
				<p class="mb-4">We implement security measures including JWT authentication, encrypted connections, and user-level data isolation. However, no system is 100% secure, and we cannot guarantee absolute security.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">9. Cookies</h3>
				<p class="mb-4">The Service uses session cookies for authentication. These are essential for the Service to function and cannot be disabled without affecting your ability to use the Service.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">10. Children's Privacy</h3>
				<p class="mb-4">The Service is not intended for children under 16. We do not knowingly collect data from children under 16.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">11. Changes to This Policy</h3>
				<p class="mb-4">We may update this policy at any time. Changes will be posted on this page with an updated date.</p>

				<h3 class="mb-2 text-sm font-medium text-[#e2e8f0]">12. Contact</h3>
				<p>For privacy-related inquiries, contact us through the Service.</p>
			</section>
		{/if}
	</div>
</div>
